"use client";

import React, { useState, useRef } from "react";
import {
  FileText,
  Sparkles,
  Download,
  Copy,
  Check,
  AlertTriangle,
  ChevronDown,
  Loader2,
  Scale,
  FileSignature,
  ScrollText,
  Stamp,
  BookOpen,
} from "lucide-react";
import { useAuth } from "../../context/AuthContext";
import { useLanguage } from "../../context/LanguageContext";

const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL || "https://justicepal-production.up.railway.app";

const DOCUMENT_TYPES = [
  { id: "demand-letter", label: "Demand Letter", labelSi: "ඉල්ලුම් ලිපිය", icon: FileSignature, description: "Formal letter demanding payment or action" },
  { id: "affidavit", label: "Affidavit", labelSi: "දිවුරුම් ප්‍රකාශය", icon: Stamp, description: "Sworn statement of facts for court proceedings" },
  { id: "power-of-attorney", label: "Power of Attorney", labelSi: "බලපත්‍රය", icon: ScrollText, description: "Legal authorization to act on someone's behalf" },
  { id: "rental-agreement", label: "Rental Agreement", labelSi: "කුලී ගිවිසුම", icon: BookOpen, description: "Contract between landlord and tenant" },
  { id: "legal-notice", label: "Legal Notice", labelSi: "නීතිමය දැනුම් දීම", icon: AlertTriangle, description: "Formal notice of legal action or dispute" },
  { id: "contract", label: "General Contract", labelSi: "සාමාන්‍ය ගිවිසුම", icon: FileText, description: "Custom business or personal agreement" },
  { id: "complaint-letter", label: "Complaint Letter", labelSi: "පැමිණිලි ලිපිය", icon: Scale, description: "Formal complaint to an authority or institution" },
];

const t = {
  en: {
    title: "AI Document Drafting",
    subtitle: "Generate professional first drafts of common legal documents using AI",
    selectType: "Select Document Type",
    caseDetails: "Describe Your Case Details",
    caseDetailsPlaceholder: "Provide details about your situation. For example:\n\n• The parties involved\n• Key facts and dates\n• What outcome you're seeking\n• Any relevant agreements or contracts",
    clientName: "Your Name (Client)",
    clientNamePlaceholder: "e.g., Nadeesha Perera",
    lawyerName: "Attorney Name (optional)",
    lawyerNamePlaceholder: "e.g., Mr. K. Perera, Attorney-at-Law",
    additionalNotes: "Additional Notes (optional)",
    additionalNotesPlaceholder: "Any specific requirements or clauses to include...",
    generate: "Generate Document Draft",
    generating: "AI is drafting your document...",
    generatedDoc: "Generated Document",
    copy: "Copy to Clipboard",
    copied: "Copied!",
    download: "Download as Text",
    disclaimer: "⚠️ AI Disclaimer",
    disclaimerText: "This document was generated by AI and is intended as a first draft only. It must be reviewed and finalized by a qualified Sri Lankan legal professional before use in any legal proceedings.",
    newDraft: "Draft Another Document",
  },
  si: {
    title: "AI ලේඛන කෙටුම්පත්",
    subtitle: "AI භාවිතයෙන් සාමාන්‍ය නීති ලේඛනවල වෘත්තීය පළමු කෙටුම්පත් ජනනය කරන්න",
    selectType: "ලේඛන වර්ගය තෝරන්න",
    caseDetails: "ඔබේ නඩු විස්තර විස්තර කරන්න",
    caseDetailsPlaceholder: "ඔබේ තත්ත්වය ගැන විස්තර සපයන්න...",
    clientName: "ඔබේ නම (සේවාලාභී)",
    clientNamePlaceholder: "උදා: නදීෂා පෙරේරා",
    lawyerName: "නීතිඥ නම (විකල්ප)",
    lawyerNamePlaceholder: "උදා: Mr. K. Perera, Attorney-at-Law",
    additionalNotes: "අමතර සටහන් (විකල්ප)",
    additionalNotesPlaceholder: "ඇතුළත් කළ යුතු විශේෂ අවශ්‍යතා...",
    generate: "ලේඛන කෙටුම්පත ජනනය කරන්න",
    generating: "AI ඔබේ ලේඛනය කෙටුම්පත් කරමින්...",
    generatedDoc: "ජනනය කළ ලේඛනය",
    copy: "පිටපත් බෝඩයට",
    copied: "පිටපත් කළා!",
    download: "පෙළ ලෙස බාගන්න",
    disclaimer: "⚠️ AI සටහන",
    disclaimerText: "මෙම ලේඛනය AI මගින් ජනනය කළ අතර එය පළමු කෙටුම්පත ලෙස පමණක් අදහස් කෙරේ.",
    newDraft: "තවත් ලේඛනයක් කෙටුම්පත් කරන්න",
  },
};

export default function DocumentDraftingPage() {
  const { user } = useAuth();
  const { lang } = useLanguage();
  const tx = t[lang as keyof typeof t] || t.en;

  const [selectedType, setSelectedType] = useState("");
  const [caseDetails, setCaseDetails] = useState("");
  const [clientName, setClientName] = useState("");
  const [lawyerName, setLawyerName] = useState("");
  const [additionalNotes, setAdditionalNotes] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedDraft, setGeneratedDraft] = useState("");
  const [copied, setCopied] = useState(false);
  const [typeDropdownOpen, setTypeDropdownOpen] = useState(false);
  const resultRef = useRef<HTMLDivElement>(null);

  const selectedDocType = DOCUMENT_TYPES.find((d) => d.id === selectedType);

  const handleGenerate = async () => {
    if (!selectedType || !caseDetails.trim()) return;
    setIsGenerating(true);
    setGeneratedDraft("");

    try {
      const token = await user?.getIdToken();
      const res = await fetch(`${BACKEND_URL}/api/ai/draft-document`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          documentType: selectedDocType?.label || selectedType,
          caseDetails: caseDetails.trim(),
          clientName: clientName.trim() || undefined,
          lawyerName: lawyerName.trim() || undefined,
          additionalNotes: additionalNotes.trim() || undefined,
        }),
      });

      if (!res.ok) throw new Error("Failed to generate document");
      const data = await res.json();
      setGeneratedDraft(data.draft);

      // Scroll to result
      setTimeout(() => {
        resultRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
      }, 200);
    } catch (error) {
      console.error("Document drafting error:", error);
      setGeneratedDraft("An error occurred while generating the document. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generatedDraft);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([generatedDraft], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${selectedType || "legal-document"}-draft.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleReset = () => {
    setGeneratedDraft("");
    setCaseDetails("");
    setClientName("");
    setLawyerName("");
    setAdditionalNotes("");
    setSelectedType("");
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  return (
    <div className="min-h-screen bg-[#F8FAFC] pt-[80px]">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 py-8">
        {/* Header */}
        <div className="text-center mb-10">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-gradient-to-br from-[#1B3A6B] to-[#112549] rounded-2xl mb-4 shadow-lg shadow-blue-900/20">
            <FileText className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">{tx.title}</h1>
          <p className="text-gray-500 max-w-lg mx-auto">{tx.subtitle}</p>
        </div>

        {/* Form */}
        {!generatedDraft && (
          <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6 sm:p-8 space-y-6 animate-fade-in">
            {/* Document Type Selector */}
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">{tx.selectType}</label>
              <div className="relative">
                <button
                  type="button"
                  onClick={() => setTypeDropdownOpen(!typeDropdownOpen)}
                  className="w-full flex items-center justify-between px-4 py-3.5 rounded-xl border border-gray-200 bg-gray-50 hover:bg-white transition-colors text-left"
                >
                  {selectedDocType ? (
                    <span className="flex items-center gap-3">
                      <selectedDocType.icon className="w-5 h-5 text-[#1B3A6B]" />
                      <span>
                        <span className="font-semibold text-gray-900">{lang === "si" ? selectedDocType.labelSi : selectedDocType.label}</span>
                        <span className="text-xs text-gray-400 ml-2">— {selectedDocType.description}</span>
                      </span>
                    </span>
                  ) : (
                    <span className="text-gray-400">{tx.selectType}...</span>
                  )}
                  <ChevronDown className={`w-5 h-5 text-gray-400 transition-transform ${typeDropdownOpen ? "rotate-180" : ""}`} />
                </button>

                {typeDropdownOpen && (
                  <div className="absolute z-20 mt-2 w-full bg-white rounded-xl border border-gray-200 shadow-xl overflow-hidden">
                    {DOCUMENT_TYPES.map((doc) => (
                      <button
                        key={doc.id}
                        onClick={() => { setSelectedType(doc.id); setTypeDropdownOpen(false); }}
                        className={`w-full flex items-center gap-3 px-4 py-3.5 text-left hover:bg-blue-50 transition-colors border-b border-gray-50 last:border-0 ${selectedType === doc.id ? "bg-blue-50" : ""}`}
                      >
                        <doc.icon className="w-5 h-5 text-[#1B3A6B] flex-shrink-0" />
                        <div>
                          <p className="font-semibold text-gray-900 text-sm">{lang === "si" ? doc.labelSi : doc.label}</p>
                          <p className="text-xs text-gray-400">{doc.description}</p>
                        </div>
                      </button>
                    ))}
                  </div>
                )}
              </div>
            </div>

            {/* Case Details */}
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">{tx.caseDetails}</label>
              <textarea
                value={caseDetails}
                onChange={(e) => setCaseDetails(e.target.value)}
                placeholder={tx.caseDetailsPlaceholder}
                rows={6}
                className="w-full px-4 py-3 rounded-xl border border-gray-200 bg-gray-50 focus:bg-white focus:border-[#1B3A6B] focus:ring-2 focus:ring-blue-100 outline-none transition-all resize-none text-sm"
              />
            </div>

            {/* Client & Lawyer Names */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">{tx.clientName}</label>
                <input
                  type="text"
                  value={clientName}
                  onChange={(e) => setClientName(e.target.value)}
                  placeholder={tx.clientNamePlaceholder}
                  className="w-full px-4 py-3 rounded-xl border border-gray-200 bg-gray-50 focus:bg-white focus:border-[#1B3A6B] focus:ring-2 focus:ring-blue-100 outline-none transition-all text-sm"
                />
              </div>
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">{tx.lawyerName}</label>
                <input
                  type="text"
                  value={lawyerName}
                  onChange={(e) => setLawyerName(e.target.value)}
                  placeholder={tx.lawyerNamePlaceholder}
                  className="w-full px-4 py-3 rounded-xl border border-gray-200 bg-gray-50 focus:bg-white focus:border-[#1B3A6B] focus:ring-2 focus:ring-blue-100 outline-none transition-all text-sm"
                />
              </div>
            </div>

            {/* Additional Notes */}
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">{tx.additionalNotes}</label>
              <textarea
                value={additionalNotes}
                onChange={(e) => setAdditionalNotes(e.target.value)}
                placeholder={tx.additionalNotesPlaceholder}
                rows={3}
                className="w-full px-4 py-3 rounded-xl border border-gray-200 bg-gray-50 focus:bg-white focus:border-[#1B3A6B] focus:ring-2 focus:ring-blue-100 outline-none transition-all resize-none text-sm"
              />
            </div>

            {/* Submit */}
            <button
              onClick={handleGenerate}
              disabled={!selectedType || !caseDetails.trim() || isGenerating}
              className="w-full py-4 bg-gradient-to-r from-[#1B3A6B] to-[#112549] text-white rounded-xl font-semibold shadow-lg shadow-blue-900/20 disabled:opacity-50 disabled:cursor-not-allowed hover:shadow-xl hover:-translate-y-0.5 transition-all flex items-center justify-center gap-2"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  {tx.generating}
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5" />
                  {tx.generate}
                </>
              )}
            </button>
          </div>
        )}

        {/* Generated Result */}
        {generatedDraft && (
          <div ref={resultRef} className="space-y-6 animate-fade-in">
            {/* Disclaimer Banner */}
            <div className="bg-amber-50 border border-amber-200 rounded-2xl p-5 flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
              <div>
                <p className="font-semibold text-amber-800 text-sm mb-1">{tx.disclaimer}</p>
                <p className="text-amber-700 text-xs leading-relaxed">{tx.disclaimerText}</p>
              </div>
            </div>

            {/* Document Output */}
            <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
              <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100 bg-gray-50/50">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-gradient-to-br from-[#1B3A6B] to-[#112549] rounded-xl flex items-center justify-center">
                    <FileText className="w-5 h-5 text-white" />
                  </div>
                  <div>
                    <h3 className="font-bold text-gray-900">{tx.generatedDoc}</h3>
                    <p className="text-xs text-gray-400">{selectedDocType ? (lang === "si" ? selectedDocType.labelSi : selectedDocType.label) : selectedType}</p>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={handleCopy}
                    className="flex items-center gap-1.5 px-3 py-2 rounded-lg border border-gray-200 text-xs font-medium text-gray-600 hover:bg-gray-100 transition-colors"
                  >
                    {copied ? <Check className="w-3.5 h-3.5 text-green-500" /> : <Copy className="w-3.5 h-3.5" />}
                    {copied ? tx.copied : tx.copy}
                  </button>
                  <button
                    onClick={handleDownload}
                    className="flex items-center gap-1.5 px-3 py-2 rounded-lg border border-gray-200 text-xs font-medium text-gray-600 hover:bg-gray-100 transition-colors"
                  >
                    <Download className="w-3.5 h-3.5" />
                    {tx.download}
                  </button>
                </div>
              </div>

              <div className="p-6 sm:p-8">
                <pre className="whitespace-pre-wrap font-sans text-sm text-gray-700 leading-relaxed">
                  {generatedDraft}
                </pre>
              </div>
            </div>

            {/* New Draft Button */}
            <button
              onClick={handleReset}
              className="w-full py-3.5 bg-white border border-gray-200 text-gray-700 rounded-xl font-semibold hover:bg-gray-50 transition-all flex items-center justify-center gap-2"
            >
              <Sparkles className="w-4 h-4 text-[#F97316]" />
              {tx.newDraft}
            </button>
          </div>
        )}
      </div>

      {/* Custom animation */}
      <style jsx>{`
        @keyframes fade-in {
          from { opacity: 0; transform: translateY(16px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-fade-in {
          animation: fade-in 0.4s ease-out;
        }
      `}</style>
    </div>
  );
}
